### ISSUE TITLE
A command exists to open an AppMap with a given selected object and view identifier

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/vscode-appland#168]
Perhaps this could be exposed as optional arguments to the `Open AppMap` command? If not, another command will suffice.

**Comment by kgilpin** [comment]
@sashahonchar this is for use in VSCode.

**Comment by kgilpin** [comment]
We would like to be able to make a CodeTour step in VSCode that will open an AppMap to a specific view configuration. In order to do this, we need these things:

1) The AppMap view in VSCode must provide a view/location string that the user can copy to the clipboard
2) The AppMap extension must provide a command that configures the AppMap view with a specified view/location string. This can be the same command that opens the AppMap, or a separate command. If the AppMap is already open, it should be adjusted to match the view/location string.
