### ISSUE TITLE
Search & filtering are added to extension

### ISSUE THREAD

**Issue by typaulhus** [applandinc/vscode-appland#43]
The filters component is styled to match the Figma mockup
[Figma -> ](https://www.figma.com/file/BqZuGL8egIF37cgbvrz1Xm/vscode?node-id=372%3A429)

![search-filters](https://user-images.githubusercontent.com/123787/105046708-6d657980-5a37-11eb-80a7-4b1bac5af4b4.png)

**Comment by dustinbyrne** [comment]
Here's my idea for the filtering component:
```html
<v-text-input
  :autocomplete-items="codeObjects"
  placeholder="Filter"
  @submit="onSubmit" />
  ```
  
 - Where `autocompleteItems` provides a list of items to fill out the autocomplete (if null/empty, disable autocomplete).
 - `placeholder` is placeholder text in the input
 - `submit` is the event emitted from the component when the user presses enter or otherwise finalizes their search

**Comment by kgilpin** [comment]
Let's make sure that this is identified as a high UX priority before we
begin coding it.

I think that some strategic coordination is needed to make sure we are
focusing our efforts as much as we can.

**Comment by dustinbyrne** [comment]
From @sashahonchar:
>When user use filter and selects some class/package/function, how diagram should be changed?
>And when user will select multiple objects with filter, what he should see on the diagram?
